In [141]:
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)
from importlib import reload
import numpy as np
import torch

import net
reload(net)

<module 'net' from '/home/arpan/connectX/net.py'>

In [142]:
net = net.NeuralTrainer(4, 2, 6, 7)

In [143]:
b1 = np.random.randint(-1, 2, size=(6,7))
b2 = np.random.randint(-1, 2, size=(6,7))

stack1 = np.zeros((2, 6, 7), dtype=int)
stack1[0] = b1 == 1
stack1[1] = b1 == -1

stack2 = np.zeros((2, 6, 7), dtype=int)
stack2[0] = b2 == 1
stack2[1] = b2 == -1

stack1, stack2

(array([[[1, 1, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 1],
         [1, 0, 0, 0, 0, 1, 0]],
 
        [[0, 0, 0, 1, 0, 1, 0],
         [1, 1, 0, 0, 0, 0, 1],
         [1, 0, 0, 1, 0, 0, 0],
         [0, 0, 1, 1, 1, 0, 1],
         [1, 0, 0, 0, 1, 1, 0],
         [0, 1, 1, 0, 1, 0, 1]]]), array([[[0, 0, 1, 0, 0, 0, 1],
         [1, 0, 0, 0, 1, 0, 1],
         [0, 1, 1, 1, 0, 0, 0],
         [0, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 1, 0, 0]],
 
        [[1, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [1, 1, 0, 0, 0, 1, 1],
         [0, 0, 1, 0, 0, 1, 0]]]))

In [156]:
# examples = [(stack1, 0, 1), (stack2, 4, -1)]
# net.train(examples)
import pickle
examples = pickle.load(open('../models/jan19/running_batch.pkl', 'rb'))
# net.train(examples[-8:-7])
examples[-8]

(array([[[0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0]],
 
        [[1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0]]]), 7, 0)

In [145]:
board = torch.zeros((2, 6, 7))
print (board)
print ('--------------')
net.predict(board)
# net(torch.FloatTensor([board]))

tensor([[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]])
--------------


(array([0.19109388, 0.12490478, 0.11018408, 0.08011447, 0.20124376,
        0.13869615, 0.15376285], dtype=float32),
 array([-0.0822972], dtype=float32))

In [146]:
import torch
import torch.nn as nn
import torch.optim as optim

torch.manual_seed(42)
a = torch.randn(1, requires_grad=True, dtype=torch.float, device='cuda:0')
b = torch.randn(1, requires_grad=True, dtype=torch.float, device='cuda:0')
print(a, b)

lr = 1e-1
n_epochs = 1000

# Defines a MSE loss function
loss_fn = nn.MSELoss(reduction='mean')

optimizer = optim.SGD([a, b], lr=lr)

for epoch in range(n_epochs):
    yhat = a + b * x_train_tensor
    
    # No more manual loss!
    # error = y_tensor - yhat
    # loss = (error ** 2).mean()
    loss = loss_fn(y_train_tensor, yhat)

    loss.backward()    
    optimizer.step()
    optimizer.zero_grad()
    
print(a, b)

tensor([0.1940], device='cuda:0', requires_grad=True) tensor([0.1391], device='cuda:0', requires_grad=True)


NameError: name 'x_train_tensor' is not defined

In [ ]:
torch.tanh(torch.Tensor([-4]))

In [ ]:
pred = torch.Tensor([ 0.0509,  0.0610,  0.0368,  0.1850,  0.1318,  0.1428, -0.0637,  0.1712,
         0.1416,  0.2459,  0.3152, -0.2012, -0.1692,  0.1329,  0.1881, -0.1291,
        -0.0688,  0.0092, -0.0571,  0.3246, -0.1121]).cuda()
v = torch.Tensor([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  1.,  0.,
         0.,  0.,  0.,  0., -1.,  0., -1.]).cuda()

In [ ]:
val_criterion = nn.MSELoss(reduction="mean")

In [ ]:
val_criterion(pred, v)

In [ ]:
print (pred, pred.shape)
print (v, v.shape)