In [157]:
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir)
from importlib import reload
import numpy as np

import simulator
reload(simulator)

<module 'simulator' from '/home/arpan/connectX/simulator.py'>

In [158]:
env = simulator.ConnectX()
env.reset()
env.print_board()

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 1


In [159]:
env.step(1)
env.step(3)
env.step(2)
cp = env.create_copy()

In [160]:
env.print_board()
env.step(2)
env.step(5)
env.print_board()
cp.print_board()

[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  1  1 -1  0  0  0]] -1
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0 -1  0  0  0  0]
 [ 0  1  1 -1  0  1  0]] -1
[[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  1  1 -1  0  0  0]] -1


In [161]:
cp.hash_state()

'0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 -1 0 0 0 '

In [162]:
cp.valid_moves()

array([1, 1, 1, 1, 1, 1, 1])

In [163]:
cp.get_stack()

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0, 0]]])

In [164]:
cp.step(3)
cp.step(4)
cp.step(3)
cp.step(4)
print (cp.is_over())

False


In [165]:
test1 = np.zeros((6, 7))
test1[0, 6] = 1
test1[1, 5] = 1
test1[2, 4] = -1
test1[3, 3] = 1

cp.board = test1
cp.is_over()

False